spring:
    main:
      banner-mode: "off"
    application:
        name: module-bd-2024
    datasource:
      url: ${DB_URL}
      username: ${DB_USER} 
      password: ${DB_PASSWORD}
      driver-class-name: oracle.jdbc.driver.OracleDriver
      hikari:
        auto-commit: true
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true

logging:
  pattern:
    console: "%-5level %logger{36} - %msg%n"
#  level:
#    root: WARN

server:
  port: 8083


